add_requires("_Log_", "spdlog")
add_requires("sol2", { configs = { includes_lua = false }})

target("Example CE Plugin")
  set_kind("shared")
  add_files("*.cpp")
  -- add_includedirs("../Cheat Engine Resources/include")
  -- add_linkdirs("../Cheat Engine Resources/lib")
  -- add_links("lua53-64")
  add_deps("Cheat Engine Plugin Resources")
  add_packages("_Log_", "spdlog", "sol2")
